version: "3.9"

services:
  devops-db:
    image: postgres:latest
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - PGDATA=/data
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=nutritracker
    volumes:
      - ./containers/postgres:/data
    restart: unless-stopped

  devops-api:
    build:
      dockerfile: Dockerfile
    container_name: python-api
    depends_on: [devops-db]
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - 8001:8001
    restart: unless-stopped